export enum ViewState {
  LANDING = 'LANDING',
  DASHBOARD_HOME = 'DASHBOARD_HOME',
  DIRECTORY = 'DIRECTORY',
  EVENTS = 'EVENTS',
  AI_ASSISTANT = 'AI_ASSISTANT',
  MEMBERSHIP = 'MEMBERSHIP',
  STORIES = 'STORIES',
  PROFILE = 'PROFILE',
  DONATE = 'DONATE',
  VOLUNTEER = 'VOLUNTEER',
  GALLERY = 'GALLERY',
  ABOUT = 'ABOUT',
}
